#!/usr/bin/env bash
# wrapper/deploy/edge-webhook/install.sh — one-time edge webhook setup
# (v1.2.0e.1 NEW per D6 + L8 mitigation)
#
# Run on each edge host:
#   ssh <host> 'bash /opt/fish-harness/wrapper/deploy/edge-webhook/install.sh'
#
# Steps:
#   1. Ensure `tsx` is available (needed by systemd unit's `node --import tsx`).
#      Wrapper's package.json doesn't pin tsx as a prod dep; install.sh
#      installs it globally (one-shot). Skip if already present.
#   2. Generate 32-byte random secret (hex) → write /etc/edge-webhook.env (chmod 600)
#   3. Install systemd unit `edge-webhook.service`
#   4. daemon-reload + enable + start
#   5. Print secret to stdout — operator MUST copy this to
#      GitHub Secrets → EDGE_WEBHOOK_SECRET_<host> (e.g., EDGE_WEBHOOK_SECRET_edge1)
#
# After install, expose /webhook via Tailscale Funnel per docs/deploy/6host-deploy.md §2.3

set -euo pipefail

ENV_FILE="/etc/edge-webhook.env"
SERVICE_FILE="/etc/systemd/system/edge-webhook.service"

# Per-host compose file selector (1-5, default 1). Each edge has its own
# compose file (edge1.yml / edge2.yml / ...). Override by passing EDGE_NUM
# as the first argument: `EDGE_NUM=2 bash install.sh` or `bash install.sh 2`.
EDGE_NUM="${1:-${EDGE_NUM:-1}}"

echo "[edge-webhook-install] using EDGE_NUM=$EDGE_NUM (compose=edge${EDGE_NUM}.yml)"

echo "[edge-webhook-install] ensuring tsx is installed..."
if ! command -v tsx >/dev/null 2>&1; then
  if command -v npm >/dev/null 2>&1; then
    echo "  installing tsx globally via npm..."
    npm install -g tsx >/dev/null 2>&1 || {
      echo "  WARN: global npm install failed; falling back to local"
      (cd /opt/fish-harness/wrapper && npm install --no-save tsx >/dev/null 2>&1) || true
    }
  else
    echo "  WARN: npm not found; cannot auto-install tsx. Install it manually or the webhook won't start."
  fi
fi

echo "[edge-webhook-install] generating 32-byte secret..."
SECRET=$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')

echo "[edge-webhook-install] writing $ENV_FILE (chmod 600)..."
cat > "$ENV_FILE" <<EOF
# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Per-host HMAC secret + compose selector for edge webhook.
# Operator must copy the EDGE_WEBHOOK_SECRET value to GitHub secrets.
EDGE_WEBHOOK_SECRET=$SECRET
EDGE_COMPOSE_FILE=/opt/fish-harness/deploy/6host-compose.edge${EDGE_NUM}.yml
# v1.2.0g NEW (per G1): per-host wrapper container name for Step 5 docker restart.
# Step 5 fires `docker restart <container>` after Step 4 self-restart to reload
# in-memory bind-mount code (closes v1.2.0f NEW M-class gap). Defaults to
# harness-edge1-wrapper if env var missing. For existing edges, append manually:
#   echo "EDGE_WRAPPER_CONTAINER=harness-edgeN-wrapper" >> /etc/edge-webhook.env
#   systemctl restart edge-webhook.service
# DO NOT re-run install.sh on existing edges — it regenerates EDGE_WEBHOOK_SECRET
# and breaks the GitHub webhook HMAC signature.
EDGE_WRAPPER_CONTAINER=harness-edge${EDGE_NUM}-wrapper
EOF
chmod 600 "$ENV_FILE"
chown root:root "$ENV_FILE"

echo "[edge-webhook-install] installing systemd unit..."
cp "$(dirname "$0")/edge-pull.service" "$SERVICE_FILE"
chmod 644 "$SERVICE_FILE"

echo "[edge-webhook-install] daemon-reload + enable + start..."
systemctl daemon-reload
systemctl enable --now edge-webhook

echo ""
echo "============================================================"
echo "  EDGE_WEBHOOK_SECRET (copy to GitHub):"
echo "  $SECRET"
echo "============================================================"
echo ""
echo "Next steps:"
echo "  1. GitHub repo → Settings → Secrets and variables → Actions"
echo "     Name: EDGE_WEBHOOK_SECRET_<host>  (e.g., EDGE_WEBHOOK_SECRET_edge1)"
echo "     Value: the secret printed above"
echo "  2. Tailscale Funnel (per docs/deploy/6host-deploy.md §2.3):"
echo "     tailscale funnel --bg --set-path=/webhook --https=443 \\"
echo "       http://127.0.0.1:7777"
echo ""
echo "Verify:"
echo "  systemctl status edge-webhook --no-pager"
echo "  journalctl -u edge-webhook -n 20 --no-pager"
