#!/usr/bin/env bash
# wrapper/deploy/edge-webhook/install.sh — one-time edge webhook setup
# (v1.2.0e.1 NEW per D6 + L8 mitigation)
#
# Run on each edge host:
#   ssh <host> 'bash /opt/fish-harness/wrapper/deploy/edge-webhook/install.sh'
#
# Steps:
#   1. Generate 32-byte random secret (hex) → write /etc/edge-webhook.env (chmod 600)
#   2. Install systemd unit `edge-webhook.service` (or .path for drop-in)
#   3. daemon-reload + enable + start
#   4. Print secret to stdout — operator MUST copy this to
#      GitHub Secrets → EDGE_WEBHOOK_SECRET_<host> (e.g., EDGE_WEBHOOK_SECRET_edge1)
#
# After install, expose /webhook via Tailscale Funnel per docs/deploy/6host-deploy.md §2.3

set -euo pipefail

ENV_FILE="/etc/edge-webhook.env"
SERVICE_FILE="/etc/systemd/system/edge-webhook.service"

echo "[edge-webhook-install] generating 32-byte secret..."
SECRET=$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')

echo "[edge-webhook-install] writing $ENV_FILE (chmod 600)..."
cat > "$ENV_FILE" <<EOF
# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Per-host HMAC secret for edge webhook. Operator must copy to GitHub secrets.
EDGE_WEBHOOK_SECRET=$SECRET
EOF
chmod 600 "$ENV_FILE"
chown root:root "$ENV_FILE"

echo "[edge-webhook-install] installing systemd unit..."
cp "$(dirname "$0")/edge-pull.service" "$SERVICE_FILE"
chmod 644 "$SERVICE_FILE"

echo "[edge-webhook-install] daemon-reload + enable + start..."
systemctl daemon-reload
systemctl enable --now edge-webhook

echo ""
echo "============================================================"
echo "  EDGE_WEBHOOK_SECRET (copy to GitHub):"
echo "  $SECRET"
echo "============================================================"
echo ""
echo "Next steps:"
echo "  1. GitHub repo → Settings → Secrets and variables → Actions"
echo "     Name: EDGE_WEBHOOK_SECRET_<host>  (e.g., EDGE_WEBHOOK_SECRET_edge1)"
echo "     Value: the secret printed above"
echo "  2. Tailscale Funnel (per docs/deploy/6host-deploy.md §2.3):"
echo "     tailscale funnel --bg --set-path=/webhook --https=443 \\"
echo "       http://127.0.0.1:7777"
echo ""
echo "Verify:"
echo "  systemctl status edge-webhook --no-pager"
echo "  journalctl -u edge-webhook -n 20 --no-pager"
